# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - D:/db/postgresql/data:/var/lib/postgresql/data
      - D:/db/postgresql/postgresql.conf:/etc/postgresql.conf